title: Baeg Lab
description: Gyeong Hun Baeg Lab at the University of Macau
baseurl: "/baeglab"
url: "https://mickeyruess.github.io"

email: your-email@um.edu.mo
author: Henry Kwok

include:
  - _pages

sass:
  sass_dir: _sass

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true
